server:
  port: 8099 #服务端口
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.97.223.130:9999/eureka/
#      defaultZone: http://localhost:8090/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:sqlite:portal.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      format_sql: true