server:
  port: 8090

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  server:
    enableSelfPreservation: false