server:
  port: 8088 #服务端口
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.97.223.130:9999/eureka/
#      defaultZone: http://localhost:8090/eureka/
spring:
  application:
    name: user-client